language: python
python:
    - 3.8
install:
    - pip install -r requirements.txt
script:
    - python manage.py test
deploy:
    provider: heroku
    api_key: $HEROKU_API_KEY
    app: hicomf
    run: python manage.py migrate
    on: master