language: python
python:
    - 3.8
install:
    - pip install -r requirements.txt
services:
  - postgresql
before_script:
  - psql -c 'create database test_db;' -U postgres
script:
    - python manage.py test mains.tests
deploy:
    provider: heroku
    api_key: $HEROKU_API_KEY
    app: hicomf
    run: python manage.py migrate
    on: master