# Generated by Django 3.1.2 on 2020-10-04 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mains', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendshiprequest',
            name='accepted',
        ),
    ]
