# Generated by Django 3.1.2 on 2020-10-04 07:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mains', '0002_remove_friendshiprequest_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendshiprequest',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 4, 7, 45, 53, 346501, tzinfo=utc), editable=False),
        ),
    ]
