# Generated by Django 3.1.2 on 2020-10-20 05:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mains', '0014_comment_like_photo_photoalbum_post_share'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='by_user',
        ),
        migrations.RemoveField(
            model_name='like',
            name='by_user',
        ),
        migrations.RemoveField(
            model_name='share',
            name='by_user',
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='auth.user', verbose_name='by user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='like',
            name='user',
            field=models.ForeignKey(default='123', on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='auth.user', verbose_name='by user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='share',
            name='user',
            field=models.ForeignKey(default=123123, on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='auth.user', verbose_name='by user'),
            preserve_default=False,
        ),
    ]
